### ISSUE TITLE
Chrome Browser processes a single request twice!

### ISSUE THREAD

**Issue by lubred** [pvginkel/NHttp#11]
There seem to be an issue with Chrome browser. Requests made with Chrome browser is processed twice in the Request Received event for every single request.
The first processing is the valid one. The second processing is not valid - gives error "Object reference not set to an instance of an object"

Other browsers processes the request just once.

See code snippet below.

**Private Sub OnWebRequestReceived(sender As Object, e As HttpRequestEventArgs)**

```
    kknntt += 1

    Dim sMobileNo, sMessageTxt, sSenderID, sSourceToken, ret As String

    Using Response = New StreamWriter(e.Response.OutputStream)

        Try
            sMobileNo = e.Request.QueryString.GetValues("mobileno").GetValue(0)
            sMessageTxt = e.Request.QueryString.GetValues("messagetext").GetValue(0)
            sSenderID = e.Request.QueryString.GetValues("senderid").GetValue(0)
            sSourceToken = e.Request.QueryString.GetValues("token").GetValue(0)
            ret = "OK"
            Response.Write(ret)
        Catch ex As Exception
            ret = "[HTTPWebService Error] - " & ex.Message & Environment.NewLine & ex.StackTrace
            EventLogger.WriteEntry(ret, EventLogEntryType.Error)
            MessageLog(ret, "APPLICATION.ERROR")
            Response.Write(String.Format("{0}#ERROR#{1}", sMobileNo, "Unable to process."))
        End Try
    End Using
    MessageLog(kknntt.ToString & " - " & ret)
End Sub`
```

**Comment by rroa** [comment]
I'd recommend checking the network pane on your Developer Tools. It is most likely that Chrome is making a request for the **.favicon** file automatically when your path is not made to an explicit resource.

You can read a discussion about it [here](http://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests).

**Comment by lubred** [comment]
Hello Raul,

Thank you for your response. Yes you are right about the .favicon being the cause of the problem.

However, please can you direct me on how to use images on the web pages being served by the package. I am not able to show images in the body of my pages. A sample snippet/code will help me a lot.

Thank you.

Chris

**Comment by rroa** [comment]
Hello @lubred I'm sorry it took me long to respond back. (I'm not an official maintainer of the code so I don't get regular notifications for threads unless you use the mention feature :)

Could you share the HTML document you're using to render the images? I'm not sure on how you're trying to achieve it.

**Comment by pvginkel** [comment]
The following code gives an example on how to implement this:

    if (e.Request.Path == "/favicon.ico")
    {
        using (var stream = File.OpenRead("favicon.ico"))
        {
            stream.CopyTo(e.Response.OutputStream);
        }
        return;
    }

If you do something like this in the beginning of the `RequestReceived` event handler, you can specifically handle the favicon.
