### ISSUE TITLE
Is there a way to send out the StatusCode 200?

### ISSUE THREAD

**Issue by ZillionPrey** [pvginkel/NHttp#14]
Hello, first of all. Awesome easy to use Lib!

My question is, can i send out a StatusCode 200 manually?

**Comment by pvginkel** [comment]
Yup, just use `e.Response.Status` for this. As a test, you can update `Program.Main` in the `NHttp.Demo` project:

    server.RequestReceived += (s, e) =>
    {
        // The response must be written to e.Response.OutputStream.
        // When writing text, a StreamWriter can be used.

        using (var writer = new StreamWriter(e.Response.OutputStream))
        {
            writer.Write("Hello world!");
        }

        e.Response.Status = "200 We're OK!"; // <--- ADDED
    };

This gives you:

![image](https://user-images.githubusercontent.com/828966/28154390-36b94480-67aa-11e7-953d-f909ea79975a.png)
