### ISSUE TITLE
Works on machine, Unable to access from Lan

### ISSUE THREAD

**Issue by spali90** [pvginkel/NHttp#20]
Set endpoint as follows
 server.EndPoint = new IPEndPoint(IPAddress.Loopback, 80);

App is accessible over 127.0.0.1 but not with Lan IP.

**Comment by pvginkel** [comment]
Try `IPAddress.Any` instead of `IPAddress.Loopback`.

**Comment by spali90** [comment]
still the same, should i do anything with firewall ?

**Comment by pvginkel** [comment]
I'm not sure. I do know it needs to be Any to work at all, but beyond that
it's probably configuration yes.
