### ISSUE TITLE
Server silently crashes occasionally

### ISSUE THREAD

**Issue by aplex** [pvginkel/NHttp#5]
From time to time, server stops responding to any requests. When this happens, there are no active threads related to NHttp.

Here is an example log:

5:48:13 HttpServer Starting HTTP server at 127.0.0.1:12345 
5:48:13 HttpServer HTTP server running at 127.0.0.1:12345 
5:48:14 HttpClient BeginRead failed  
5:48:14 HttpServer Failed to accept TCP client 
5:48:15 HttpClient Accepted request '...'
<~20 Accepted request messages>
5:52:08 HttpClient Accepted request '...'
5:52:18 HttpClient Accepted request '...'
5:52:29 HttpClient Accepted request '...'
5:52:39 HttpClient Accepted request '...'
5:52:39 HttpClient Failed to read from the HTTP connection 

After that, no further request are accepted by the server and they all timeout on the client side.

Here is a dump of HttpServer properties from debugger at that time. _listner field is expanded:

-		httpServer	{NHttp.HttpServer}	NHttp.HttpServer
+		_clients	Count = 0	System.Collections.Generic.Dictionary<NHttp.HttpClient,bool>
+		_clientsChangedEvent	{System.Threading.AutoResetEvent}	System.Threading.AutoResetEvent
		_disposed	false	bool
-		_listener	{System.Net.Sockets.TcpListener}	System.Net.Sockets.TcpListener
		Active	true	bool
		ExclusiveAddressUse	false	bool
+		LocalEndpoint	{127.0.0.1:29235}	System.Net.EndPoint {System.Net.IPEndPoint}
		m_Active	true	bool
		m_ExclusiveAddressUse	false	bool
+		m_ServerSocket	{System.Net.Sockets.Socket}	System.Net.Sockets.Socket
+		m_ServerSocketEP	{127.0.0.1:12345}	System.Net.IPEndPoint
-		Server	{System.Net.Sockets.Socket}	System.Net.Sockets.Socket
		addressFamily	InterNetwork	System.Net.Sockets.AddressFamily
		AddressFamily	InterNetwork	System.Net.Sockets.AddressFamily
		Available	0	int
		Blocking	true	bool
+		Caches	{System.Net.Sockets.Socket.CacheSet}	System.Net.Sockets.Socket.CacheSet
		CanUseAcceptEx	false	bool
		CleanedUp	false	bool
		Connected	false	bool
		DontFragment	true	bool
+		DualMode	'httpServer._listener.Server.DualMode' threw an exception of type 'System.NotSupportedException'	bool {System.NotSupportedException}
+		EnableBroadcast	'httpServer._listener.Server.EnableBroadcast' threw an exception of type 'System.Net.Sockets.SocketException'	bool {System.Net.Sockets.SocketException}
		ExclusiveAddressUse	false	bool
+		Handle	3652	System.IntPtr
		IsBound	true	bool
		IsDualMode	false	bool
		isListening	true	bool
+		LingerState	{System.Net.Sockets.LingerOption}	System.Net.Sockets.LingerOption
+		LocalEndPoint	{127.0.0.1:12345}	System.Net.EndPoint {System.Net.IPEndPoint}
+		m_AcceptQueueOrConnectResult	Count = 0	object {System.Collections.Queue}
+		m_AsyncEvent	{System.Threading.ManualResetEvent}	System.Threading.ManualResetEvent
		m_BlockEventBits	FdAccept	System.Net.Sockets.AsyncEventBits
		m_BoundToThreadPool	true	bool
+		m_Caches	{System.Net.Sockets.Socket.CacheSet}	System.Net.Sockets.Socket.CacheSet
		m_CloseTimeout	-1	int
+		m_DynamicWinsockMethods	{System.Net.Sockets.DynamicWinsockMethods}	System.Net.Sockets.DynamicWinsockMethods
+		m_Handle	{System.Net.SafeCloseSocket}	System.Net.SafeCloseSocket
		m_IntCleanedUp	0	int
		m_IsConnected	false	bool
		m_IsDisconnected	false	bool
		m_NonBlockingConnectInProgress	false	bool
		m_NonBlockingConnectRightEndPoint	null	System.Net.EndPoint
+		m_PermittedRemoteAddress	null	System.Net.SocketAddress
		m_ReceivingPacketInformation	false	bool
		m_RegisteredWait	null	System.Threading.RegisteredWaitHandle
		m_RemoteEndPoint	null	System.Net.EndPoint
+		m_RightEndPoint	{127.0.0.1:12345}	System.Net.EndPoint {System.Net.IPEndPoint}
+		MulticastLoopback	'httpServer._listener.Server.MulticastLoopback' threw an exception of type 'System.Net.Sockets.SocketException'	bool {System.Net.Sockets.SocketException}
		NoDelay	false	bool
		ProtocolType	Tcp	System.Net.Sockets.ProtocolType
		protocolType	Tcp	System.Net.Sockets.ProtocolType
		ReceiveBufferSize	8192	int
		ReceiveTimeout	0	int
+		RemoteEndPoint	'httpServer._listener.Server.RemoteEndPoint' threw an exception of type 'System.Net.Sockets.SocketException'	System.Net.EndPoint {System.Net.Sockets.SocketException}
+		SafeHandle	{System.Net.SafeCloseSocket}	System.Net.SafeCloseSocket
		SendBufferSize	8192	int
		SendTimeout	0	int
		SocketType	Stream	System.Net.Sockets.SocketType
		socketType	Stream	System.Net.Sockets.SocketType
		Transport	Tcp	System.Net.TransportType
		Ttl	64	short
		UseOnlyOverlappedIO	false	bool
		useOverlappedIO	false	bool
		willBlock	true	bool
		willBlockInternal	true	bool
+		Static members		
		_state	Started	NHttp.HttpServerState
		_syncLock	{object}	object
-		EndPoint	{127.0.0.1:12345}	System.Net.IPEndPoint
+		base	{127.0.0.1:12345}	System.Net.EndPoint {System.Net.IPEndPoint}
+		Address	{127.0.0.1}	System.Net.IPAddress
		AddressFamily	InterNetwork	System.Net.Sockets.AddressFamily
+		m_Address	{127.0.0.1}	System.Net.IPAddress
		m_Port	12345	int
		Port	12345	int
+		Static members		
		ReadBufferSize	4096	int
-		RequestReceived	{Method = {Void <Start>b__0(System.Object, NHttp.HttpRequestEventArgs)}}	NHttp.HttpRequestEventHandler
-		base	{Method = {Void <Start>b__0(System.Object, NHttp.HttpRequestEventArgs)}}	System.MulticastDelegate {NHttp.HttpRequestEventHandler}
+		base	{Method = {Void <Start>b__0(System.Object, NHttp.HttpRequestEventArgs)}}	System.Delegate {NHttp.HttpRequestEventHandler}
+		_invocationCount	0	System.IntPtr
		_invocationList	null	object
		ServerBanner	"NHttp/0.1.7.0"	string
+		ServerUtility	{NHttp.HttpServerUtility}	NHttp.HttpServerUtility
+		ShutdownTimeout	{00:00:30}	System.TimeSpan
		State	Started	NHttp.HttpServerState
		StateChanged	null	System.EventHandler
		UnhandledException	null	NHttp.HttpExceptionEventHandler
		WriteBufferSize	4096	int

**Comment by ceilingfish** [comment]
Hi, I had a similar issue, I tracked it down to HTTP keep alive. My client was sending

Connection: Keep-Alive

In it's request headers, and NHttp was not responding with any confirmation or denial that it supported keep alives. By default this means that the client assumes that keep alives are supported. I added

Connection: close

To the response headers and my problems went away. Better support for keep alives would be awesome, I'll add it if I get a chance.

**Comment by pvginkel** [comment]
Thanks for the research. If I'm correct, I should do the following:

* When I receive a `Connection: Keep-Alive` as part of the request headers;
* I should send a `Connection: Close` as part of the response.

Is this correct?

**Comment by tekhedd** [comment]
Talking HTTP 1.1 here

You should send Connection:Close any time you close a keep-alive session. ... er... I think. Let me look it up.  " If the server chooses to close the connection immediately after sending the response, it SHOULD send a Connection header including the connection-token close. "  Yeah. (http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html) 

I think that if the client sends Connection: Close, you do not have to send the Close header back with your response, and can simply close the connection.

Keep-Alives persistent connections are a requirement for my project... may have to look at the code.

**Comment by pvginkel** [comment]
So, I tested this. I send the following request to google.com: (You can easily try this with PuTTY selecting port 80, Raw and Never close window on exit.)

```
GET / HTTP/1.1
Host: google.com
```

And, it just closed my connection (after 30 seconds or something like that), no `Connection: Close` and no `Connection: Keep-Alive`.

Then I tried:

```
GET / HTTP/1.1
Host: google.com
Connection: Keep-Alive
```

And it also just closed my connection (also after 30 seconds or something like that) also no `Connection: Close` and no `Connection: Keep-Alive`.

I'm not sure, but I don't think I'm violating the specifications here.

However, this really was not the problem. The problem may be that I'm never forcibly closing HTTP connections. I depend on the client to close it. This means that if the client doesn't close the connect, and I wont, they both stay open indefinitely. I've implemented a timeout manager to fix this. The default read (incl. keep-alive) and write timeouts are 90 seconds, which should be fine.

I've pushed 0.1.9.0 to NuGet. Have a look to see whether this helps.
